### ISSUE TITLE
`zcat` works differently on mac

### ISSUE THREAD

**Issue by AI-Mozi** [postmodern/wordlist.rb#23]
Instead of:
```
$ zcat foo.txt.gz 
```
it needs to be run as:
```
$ zcat < foo.txt.gz 
```

**Comment by postmodern** [comment]
CI is now all green on macOS after changing every `*cat` command to `*cat < path/to/file`. Merging into main and releasing a patch release.

**Comment by postmodern** [comment]
Fixed in 1.0.3.
